name: $(BuildDefinitionName)_$(Date:yyyyMMdd)$(Rev:.rr)

trigger:
  batch: true
  branches:
    include: [master, test-me-*]
  tags:
    include: ['*']

pr:
  branches:
    include: [master, development]

jobs:
  - template: jobs/run-tox.yml
    parameters:
      tox_envs:
        pre-commit:
          display_name: pre_commit
