parameters:
  dependsOn: []
  toxenv: 'coverage'
  tox_version: ''
  tox_python: '3.8'

jobs:
  - job: report_coverage
    pool: {vmImage: "ubuntu-latest"}
    condition: always()
    dependsOn: ${{ parameters.dependsOn }}
    variables:
      TMPDIR: $(Build.BinariesDirectory)
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      TOXENV: ${{ parameters.toxenv }}
      send_cov_to_codeclimate: ${{ parameters.send_cov_to_codeclimate }}
    steps:
      - task: DownloadBuildArtifacts@0
        displayName: download coverage files for run
        inputs:
          buildType: current
          downloadType: specific
          itemPattern: coverage-*/*
          downloadPath: $(Build.StagingDirectory)

      - task: UsePythonVersion@0
        displayName: setup python
        inputs:
          versionSpec: ${{ parameters.tox_python }}

      - script: |
          python -c '
          from pathlib import Path
          import shutil

          from_folder = Path("$(Build.StagingDirectory)")
          destination_folder = Path("$(System.DefaultWorkingDirectory)") / ".tox"
          destination_folder.mkdir()
          for coverage_file in from_folder.glob("*/.coverage"):
              destination = destination_folder / f".coverage.{coverage_file.parent.name[9:]}"
              print(f"{coverage_file} copy to {destination}")
              shutil.copy(str(coverage_file), str(destination))'
        displayName: move coverage files into .tox

      #: upgrade tox python pip, setuptools, virtualenv, wheel
      - script: python -m pip install -U --user pip
        displayName: "tox: upgrade pip"
      - script: python -m pip install -U --user setuptools virtualenv wheel
        displayName: "tox: upgrade setuptools, virtualenv, wheel"

      #: install tox for tox python
      - ${{ if parameters.tox_version }}:
        - script: ${{ format('python -m pip install -U --user --force-reinstall tox=={0}', parameters.tox_version) }}
          displayName: "${{ format('tox: install version {0} from PyPi', parameters.tox_version) }}"
      - ${{ if not(parameters.tox_version) }}:
        - script: python -m pip install -U --user --force-reinstall tox
          displayName: "tox: install newest version from PyPI"

      - script: 'python -m tox -e py -vv --sdistonly'
        displayName: run package build to ensure generated files present

      - script: 'python -m tox --notest -vv --skip-missing-interpreters false'
        displayName: generate coverage tox test environment

      - script: 'python -m tox'
        displayName: create coverage report via tox

      - task: PublishCodeCoverageResults@1
        displayName: publish overall coverage report to Azure
        inputs:
          codeCoverageTool: 'Cobertura'
          summaryFileLocation: "$(System.DefaultWorkingDirectory)/.tox/coverage.xml"
          failIfCoverageEmpty: true

#      - ${{ if eq(parameters.send_cov_to_codeclimate, true) }}:
#        - template: ../steps/publish-codeclimate.yml

      - script: |
          curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter && \
          chmod +x ./cc-test-reporter && \
          python -c '
          from xml.etree import ElementTree as et
          from pathlib import Path
          import subprocess
          from_folder = Path("$(Build.StagingDirectory)")
          for counter, coverage_file in enumerate(from_folder.glob("*/coverage.xml")):
              key = coverage_file.parent.name[9:]
              print(f"{counter}) {coverage_file}")
              try:
                  cmd = ["$(System.DefaultWorkingDirectory)/cc-test-reporter", "format-coverage",
                         str(coverage_file),
                         "-d", "-t", "coverage.py",
                         "-o", f"$(Build.StagingDirectory)/code-climate.{key}.json"]
                  print(f"\t{cmd}")
                  log = subprocess.check_output(cmd, stderr=subprocess.STDOUT, universal_newlines=True)
                  code = 0
              except subprocess.CalledProcessError as exception:
                  log, code = exception.output, exception.returncode
              finally:
                  print(code, log, "\n", sep="\n")' && \
          ./cc-test-reporter sum-coverage -d --output - \
              --parts $(ls -1 $(Build.StagingDirectory)/code-climate.*.json | wc -l) \
              $(Build.StagingDirectory)/code-climate.*.json | \
          ./cc-test-reporter -d -r 4cdceb4fb4bd47851f327963b9b225f8cbafad7a8cc25f1373c6da8b2ef371c2 \
              upload-coverage --input -
        displayName: publish code climate
        condition: and(eq(variables['system.pullrequest.isfork'], false), eq(variables.send_cov_to_codeclimate, true))
