parameters:
  python_version: '3.8'
  dependsOn: []
  custom_repository_url: ''

jobs:
  - job: publish
    dependsOn: ${{ parameters.dependsOn }}
    condition: succeeded()
    pool: {vmImage: 'ubuntu-latest'}
    variables:
      TMPDIR: $(Build.BinariesDirectory)
      PIP_DISABLE_PIP_VERSION_CHECK: '1'
      ${{ if parameters.custom_repository_url }}:
        custom_repository: true
      ${{ if not(parameters.custom_repository_url) }}:
        custom_repository: false
    steps:
      - task: UsePythonVersion@0
        displayName: setup python
        inputs:
          versionSpec: ${{ parameters.python_version }}
      - script: python -m pip install -U --user --force-reinstall poetry
        displayName: Install poetry
      - script: python -m poetry build
        displayName: Build package
      - script: python -m poetry config repositories.custom ${{ parameters.custom_repository_url }}
        displayName: Set custom repository url
        condition: eq(variables.custom_repository, true)
      - script: python -m poetry publish -r custom
        displayName: Upload to custom repository
        condition: eq(variables.custom_repository, true)
      - script: python -m poetry publish
        displayName: Upload to PyPI
        condition: ne(variables.custom_repository, true)
